### PR TITLE
Pagination

### PR DESCRIPTION
**Pull request by Kibet-mutai**
Fixes: #63

### CODE REVIEW

**Comment by Collins-Omariba** [comment]
### I have got some suggestions:
 - _pycache files should be excluded from the pull request.
 - the changes include tests, only the pagination changes  alone are expected , probably your branch wasn't up to date or something else,  check . 
 ### Merging will follow

**Comment by Kibet-mutai** [comment]
I remove database credentials from the tests file. I think that what's causing conflicts but my branch was upto date.

**Comment by Collins-Omariba** [comment]
Check #69 , The project views were changed to class based views . The conflicts in the file is due to this.

**Comment by Collins-Omariba** [comment]
You worked on the #63 without updating to the new changes. You can now check it out and create a cleaner pull request.

**Comment by Kibet-mutai** [comment]
OK

**Pull request closed without merging**
